// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: aop.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HelloString string `protobuf:"bytes,1,opt,name=hello_string,json=helloString,proto3" json:"hello_string,omitempty"`
}

func (x *CheckResultReq) Reset() {
	*x = CheckResultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResultReq) ProtoMessage() {}

func (x *CheckResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_aop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResultReq.ProtoReflect.Descriptor instead.
func (*CheckResultReq) Descriptor() ([]byte, []int) {
	return file_aop_proto_rawDescGZIP(), []int{0}
}

func (x *CheckResultReq) GetHelloString() string {
	if x != nil {
		return x.HelloString
	}
	return ""
}

type CheckResultResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode string `protobuf:"bytes,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"` //操作结果，1成功，0失败
}

func (x *CheckResultResp) Reset() {
	*x = CheckResultResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResultResp) ProtoMessage() {}

func (x *CheckResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_aop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResultResp.ProtoReflect.Descriptor instead.
func (*CheckResultResp) Descriptor() ([]byte, []int) {
	return file_aop_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResultResp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

var File_aop_proto protoreflect.FileDescriptor

var file_aop_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x54, 0x73, 0x65,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x36, 0x0a,
	0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x92, 0x01, 0x0a, 0x07, 0x41, 0x6f, 0x70, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x42, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1b, 0x2e, 0x54, 0x73, 0x65,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x54, 0x73, 0x65, 0x70, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x06, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x12,
	0x1b, 0x2e, 0x54, 0x73, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x54,
	0x73, 0x65, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aop_proto_rawDescOnce sync.Once
	file_aop_proto_rawDescData = file_aop_proto_rawDesc
)

func file_aop_proto_rawDescGZIP() []byte {
	file_aop_proto_rawDescOnce.Do(func() {
		file_aop_proto_rawDescData = protoimpl.X.CompressGZIP(file_aop_proto_rawDescData)
	})
	return file_aop_proto_rawDescData
}

var file_aop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aop_proto_goTypes = []interface{}{
	(*CheckResultReq)(nil),  // 0: TsepContent.CheckResultReq
	(*CheckResultResp)(nil), // 1: TsepContent.CheckResultResp
}
var file_aop_proto_depIdxs = []int32{
	0, // 0: TsepContent.AopTest.hello:input_type -> TsepContent.CheckResultReq
	0, // 1: TsepContent.AopTest.hello2:input_type -> TsepContent.CheckResultReq
	1, // 2: TsepContent.AopTest.hello:output_type -> TsepContent.CheckResultResp
	1, // 3: TsepContent.AopTest.hello2:output_type -> TsepContent.CheckResultResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aop_proto_init() }
func file_aop_proto_init() {
	if File_aop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResultResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aop_proto_goTypes,
		DependencyIndexes: file_aop_proto_depIdxs,
		MessageInfos:      file_aop_proto_msgTypes,
	}.Build()
	File_aop_proto = out.File
	file_aop_proto_rawDesc = nil
	file_aop_proto_goTypes = nil
	file_aop_proto_depIdxs = nil
}
